### ISSUE TITLE
Posh Server doesn't start because of missing python modules; e.g. yaml

### ISSUE THREAD

**Issue by reiniA** [nettitude/PoshC2#281]
## Description

After installing PoshC2 on Kali through the bash script, creating a new project and configuring the config file the posh-server will not start because it says the yaml module is missing. Did anyone had this issue before?

```
┌──(bob㉿helpdesk-pc)-[~]
└─$ posh 
Traceback (most recent call last):
  File "/opt/PoshC2/start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 14, in run
    client.start()
  File "/opt/PoshC2/poshc2/client/__init__.py", line 5, in start
    from poshc2.client.command_handlers.ImplantHandler import main
  File "/opt/PoshC2/poshc2/client/command_handlers/ImplantHandler.py", line 11, in <module>
    from prompt_toolkit import PromptSession
ModuleNotFoundError: No module named 'prompt_toolkit'
                                                                                                                                                                         
┌──(bob㉿helpdesk-pc)-[~]
└─$ posh-server
Traceback (most recent call last):
  File "/opt/PoshC2/start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 17, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 7, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 10, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 6, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml, glob, sys
ModuleNotFoundError: No module named 'yaml'

```

**Comment by benpturner** [comment]
Hi - did you see this PR https://github.com/nettitude/PoshC2/pull/280

**Comment by benpturner** [comment]
Might get you going. We are in the process of pushing a new version so hopefully v9 will be out soon or try installing that branch as well

**Comment by reiniA** [comment]
Thanks, this work.
