### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by sneezy-ladybug** [nettitude/PoshC2#78]
Hey, 
I'm getting the following error when I try to run posh-server or any command, really. 

Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 13, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 6, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 7, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 3, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, ClockworkSMS_APIKEY, Pushover_APIToken, Pushover_APIUser, Sounds, ClockworkSMS_MobileNumbers, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'

I've tried severally to install the module using but it seems to be installed already. 

This is the result after running: pip install pyyaml. 
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (5.1.2)

HELP!

**Comment by benpturner** [comment]
Posh-server runs in its own python virtual environment and during the install it creates this and then adds the dependencies to that via pip. 

Try running this and see what the output is.

cd /opt/PoshC2
python3 -m pipenv --python 3 run pip install -r requirements.txt

**Comment by benpturner** [comment]
So its this line "pyttsx3" in requirements.txt

**Comment by benpturner** [comment]
Remove that from requirements.txt and re-run the Install.sh

**Comment by benpturner** [comment]
I've updated this https://github.com/nettitude/PoshC2/commit/2a6407be3d4f3fd837e47a957aedbe497c66a974 for now. It only uses this library for the sound so as long as you don't want sound you will be ok.

**Comment by sneezy-ladybug** [comment]
Hey! Thanks. This worked.

**Comment by nickkilla** [comment]
So I've tried the steps above and I'm still getting no yaml module installed.

`nickkilla@box:~$ sudo posh
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 10, in run
    client.start()
  File "/opt/PoshC2/poshc2/client/__init__.py", line 5, in start
    from poshc2.client.command_handlers.ImplantHandler import main
  File "/opt/PoshC2/poshc2/client/command_handlers/ImplantHandler.py", line 5, in <module>
    from poshc2.server.DB import update_item, get_c2server_all, get_implants_all, get_tasks, get_implantdetails, new_urldetails
  File "/opt/PoshC2/poshc2/server/DB.py", line 4, in <module>
    from poshc2.server.Config import Database
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'`
