### ISSUE TITLE
bug? upload-file with blank destination name hoses posh-server

### ISSUE THREAD

**Issue by chppppp** [nettitude/PoshC2#94]
do this in posh, upload-file but leave the destination blank
```
Location file to upload: JuicyPotato.exe                                                                                                                                     
Location to upload to:                                                                                                                                                       
Uploading /opt/PoshC2_Project/payloads/JuicyPotato.exe to 
```

you perm hose your posh-server, restarting the server doesnt fix it. 
```
----------------------------------------
Exception happened during processing of request from ('10.10.10.180', 53258)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 90, in do_GET
    new_task = newTask(self.path)
  File "/opt/PoshC2/poshc2/server/Tasks.py", line 29, in newTask
    upload_file_destination = upload_args.split()[1]
IndexError: list index out of range
----------------------------------------
```

**Comment by chppppp** [comment]
Running `cleartasks` fixes this but now a new issue - upload-file will lowercase the entire source path whether you like it or not:

```
----------------------------------------
Exception happened during processing of request from ('10.10.10.180', 53517)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 90, in do_GET
    new_task = newTask(self.path)
  File "/opt/PoshC2/poshc2/server/Tasks.py", line 32, in newTask
    with open(upload_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/poshc2_project/payloads/juicypotato.exe'
----------------------------------------
```

my posh_projects is located at /opt/Posh_Projects but upload-file is automagically lower-casing my path. 

Thanks

**Comment by benpturner** [comment]
https://github.com/nettitude/PoshC2/commit/d6c1fee0bd8471a02aa2c65b4a6ca23502c2d33d

**Comment by benpturner** [comment]
Should be fixed in the lastest update above
